### PR TITLE
Update structure for rstantools

### PR DESCRIPTION
**Pull request by andrjohns**
This PR updates your package structure to fully delegate the Stan model compilation to `rstantools`, which will help ensure future compatibility

### CODE REVIEW

**Comment by demsarjure** [comment]
Hi @andrjohns! Thanks for preparing this!

**Comment by demsarjure** [comment]
@andrjohns

I am having some issues with recompiling the package after this change. It might be due to something else as I had to reinstall/update rstan and rtools as well. Here is what I did:

```
# 1. installed rtools4.2

# installed stanheaders
install.packages("StanHeaders", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))

# installed rstan
install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))

# sanity check - WORKS!
example(stan_model, package = "rstan", run.dontrun = TRUE)
```

After that if I try running `devtools::build()` on the package I get:

```
                    from stanExports_color.h:23,
                    from stanExports_color.cc:5:
   C:/Users/Jure/AppData/Local/R/win-library/4.2/BH/include/boost/math/quadrature/detail/sinh_sinh_detail.hpp:474:4: warning: non-standard suffix on floating constant [-Wpedantic]
     474 |    m_t_max = 8.88600744303961370002819023592353264e+00Q;
         |    ^~~~~~~
   In file included from stanExports_color.cc:5:
   stanExports_color.h:267:10: fatal error: stan_meta_header.hpp: No such file or directory
     267 | #include <stan_meta_header.hpp>
         |          ^~~~~~~~~~~~~~~~~~~~~~
   compilation terminated.
   make: *** [C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:258: stanExports_color.o] Error 1
   ERROR: compilation failed for package 'bayes4psy'
-  removing 'C:/Users/Jure/AppData/Local/Temp/RtmpqSvb89/Rinst57a47e3401e/bayes4psy'
         -----------------------------------
   ERROR: package installation failed
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, ...`:
! System command 'Rcmd.exe' failed
```

Thanks for any assistance!

**Comment by andrjohns** [comment]
Sorry for the delay in getting to this!

The issue is that I missed the fact that your `.gitignore` was excluding all `*.hpp` files, which caused the `stan_meta_header.hpp` file to not be included in the PR. I'll double-check that all works locally on Windows and then open a PR with the fix. Sorry about that!

**Comment by demsarjure** [comment]
No worries, thanks for the assistance. I would not be able to figure this out on my own :).

**Pull request merged**
